### ISSUE TITLE
new release with ppx on opam?

### ISSUE THREAD

**Issue by c-cube** [mfp/ocaml-sqlexpr#15]
It seems there has been a release 0.6, but it's not on opam. (Btw, does having both `estring` (with camlp4) as a dependency and ppx tools work? I thought they were incompatible)

**Comment by mfp** [comment]
I'm probably releasing 0.6.1 (0.6 branch w/o ppx, for compatibility with older OCaml, only to receive important bugfixes) and 0.7.0 (or 1.0.0 depending on the mood) w/ ppx support. And trying not to forget to request its inclusion in opam this time around :)

As for estring and ppx_tools, they're never used at a time, are they? According to _oasis, the former is used to build the sqlexpr lib and the camlp4 syntax; the latter, only for ppx_sqlexpr. Same for the omake-based build system.

**Comment by Gbury** [comment]
Any news concerning the opam releases ?

**Comment by Armael** [comment]
Ping? :) I'd also be interested in a new release.

**Comment by mfp** [comment]
OK, took me a couple attempts but should be OK now. I released 0.6.1 (performance bug fixes + faster select/iter/fold) and 0.7.1 (the same + PPX support). The 0.6 branch supports older OCaml, 0.7+ needs 4.02 or higher.

Awaiting approval, likely will be delayed because of a sqlite3 build issue that's not my fault AFAICS:
https://github.com/ocaml/opam-repository/pull/7298#issuecomment-242715257
https://github.com/ocaml/opam-repository/pull/7301

**Comment by mfp** [comment]
Both 0.6.1 and 0.7.1 have been merged into the main OPAM repository.

**Comment by Armael** [comment]
Thanks a lot!
